### ISSUE TITLE
vue 2.5加载失败

### ISSUE THREAD

**Issue by 544447** [caohuatao/vue-super-flow#14]
error  in ./node_modules/vue-super-flow/lib/index.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at D:\work\subway\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (D:\work\subway\node_modules\browserslist\index.js:132:18)
    at browserslist (D:\work\subway\node_modules\browserslist\index.js:224:16)
    at Browsers.parse (D:\work\subway\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (D:\work\subway\node_modules\autoprefixer\lib\browsers.js:52:30)
    at loadPrefixes (D:\work\subway\node_modules\autoprefixer\lib\autoprefixer.js:70:24)       
    at plugin (D:\work\subway\node_modules\autoprefixer\lib\autoprefixer.js:81:24)
    at LazyResult.run (D:\work\subway\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (D:\work\subway\node_modules\postcss\lib\lazy-result.js:192:32)    
    at LazyResult.asyncTick (D:\work\subway\node_modules\postcss\lib\lazy-result.js:204:22)    
    at D:\work\subway\node_modules\postcss\lib\lazy-result.js:197:27

 @ ./node_modules/vue-super-flow/lib/index.css 4:14-118 13:3-17:5 14:22-126
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
---------------------------------------------------------------------------------------------------------------
这是报错内容

**Comment by caohuatao** [comment]
查看你项目 browserslist 的配置。

**Comment by caohuatao** [comment]
组件编写环境为 vue 2.6 版本。 包括示例中使用的 v-slot 也是在2.6中新增的 建议使用 2.6 以上版本！
